### ISSUE TITLE
very nice

### ISSUE THREAD

**Issue by jackttcoms** [jwill9999/letuscodemvc#1]
you should add roles and permissions like below and also add forgot password and activate account!

https://sevvlor.com/post/2014/10/14/how-to-make-role-based-access-control-in-php/
https://www.sitepoint.com/role-based-access-control-in-php/

**Comment by jwill9999** [comment]
Hi jackttcoms
Thanks for your feedback this is just work in progress over the last week. I do plan to add Authentication and route guards etc to this so the links you provided will be most useful. Thank you for your feedback

**Comment by jackttcoms** [comment]
No problem 

Thanks :)
